[package]
name = "dialtone"
version = "0.1.0"
authors = ["River <22485304+actual-size@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hound = "3.4.0"